apiVersion: v1
kind: Service
metadata:
  name: {{ include "rara-app.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rara-app.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.backend.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "rara-app.componentSelectorLabels" (dict "root" . "component" "backend") | nindent 4 }}
