{{- if and .Values.memos.enabled .Values.memos.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rara-infra.fullname" . }}-memos-pg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rara-infra.componentLabels" (dict "root" . "component" "memos-pg") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.memos.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.memos.postgresql.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.memos.postgresql.persistence.size }}
{{- end }}
