apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rara-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rara-app.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secret.jwtSecret | b64enc | quote }}
