repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo +nightly fmt --all -- --check
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --workspace --all-targets --no-deps -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-check
        name: cargo check
        entry: cargo check --all --all-targets
        language: system
        pass_filenames: false
        types: [rust]
