#!/usr/bin/env bash
# init.sh — rara session-start health check
#
# Run this at the top of every new agent (or human) session. It is the single
# source of truth for "is my environment ready to code on rara?" — `just doctor`
# is a thin wrapper around this file. If a check needs to change, change it here.
#
# Exit code: 0 if every fatal check passes, non-zero otherwise. Backend
# reachability and `gh` auth are warn-only — many tasks (pure Rust refactors,
# doc edits, CI tweaks) work fine without them.

set -uo pipefail

# Resolve repo root regardless of where this is invoked from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ANSI colors — disabled when stdout is not a TTY so logs stay clean.
if [ -t 1 ]; then
    RED=$'\033[31m'
    GREEN=$'\033[32m'
    YELLOW=$'\033[33m'
    BOLD=$'\033[1m'
    RESET=$'\033[0m'
else
    RED=""
    GREEN=""
    YELLOW=""
    BOLD=""
    RESET=""
fi

FATAL_FAILURES=0

ok()    { printf '  %s[ ok ]%s   %s\n'   "$GREEN"  "$RESET" "$1"; }
warn()  { printf '  %s[warn]%s   %s\n'   "$YELLOW" "$RESET" "$1"; }
fail()  { printf '  %s[fail]%s   %s\n'   "$RED"    "$RESET" "$1"; FATAL_FAILURES=$((FATAL_FAILURES + 1)); }
section() { printf '\n%s%s%s\n' "$BOLD" "$1" "$RESET"; }

# ----------------------------------------------------------------------------
# Toolchain — fatal
# ----------------------------------------------------------------------------
section "Toolchain"

if cargo --version >/dev/null 2>&1; then
    ok "cargo: $(cargo --version)"
else
    fail "cargo not found — install via https://rustup.rs"
fi

if cargo +nightly --version >/dev/null 2>&1; then
    ok "cargo +nightly: $(cargo +nightly --version)"
else
    fail "cargo +nightly not found — run: rustup toolchain install nightly"
fi

if prek --version >/dev/null 2>&1; then
    ok "prek: $(prek --version)"
else
    fail "prek not found — install: brew install prek"
fi

# ----------------------------------------------------------------------------
# Workspace — fatal
# ----------------------------------------------------------------------------
section "Workspace"

if cargo check --workspace --all-targets >/tmp/rara-init-cargo-check.log 2>&1; then
    ok "cargo check --workspace --all-targets"
else
    fail "cargo check failed — see /tmp/rara-init-cargo-check.log"
fi

# schema.rs is @generated by `diesel print-schema`; a dirty schema relative to
# HEAD usually means a forgotten regeneration after a migration.
if git diff --quiet -- crates/rara-model/src/schema.rs 2>/dev/null; then
    ok "crates/rara-model/src/schema.rs is clean"
else
    fail "crates/rara-model/src/schema.rs has uncommitted changes — regenerate via 'diesel print-schema' and commit, or revert"
fi

# ----------------------------------------------------------------------------
# Remote backend — warn-only
# ----------------------------------------------------------------------------
section "Remote backend (warn-only)"

if curl --silent --max-time 3 -o /dev/null -w '%{http_code}' http://10.0.0.183:25555/api/health 2>/dev/null | grep -q '^200$'; then
    ok "raratekiAir backend (10.0.0.183:25555) reachable"
else
    warn "backend unreachable at http://10.0.0.183:25555/api/health — fine for Rust-only work; see docs/guides/debug.md to revive"
fi

# ----------------------------------------------------------------------------
# Agenda hint — warn-only
# ----------------------------------------------------------------------------
section "Agenda (warn-only)"

if gh auth status >/dev/null 2>&1; then
    if open_count=$(gh issue list --label agent:claude --state open --json number --jq 'length' 2>/dev/null); then
        ok "open agent:claude issues: ${open_count} (run 'just agenda' to list)"
    else
        warn "could not query open issues via gh"
    fi
else
    warn "gh auth status failed — run 'gh auth login' to enable 'just agenda'"
fi

# ----------------------------------------------------------------------------
# Verdict
# ----------------------------------------------------------------------------
echo
if [ "$FATAL_FAILURES" -eq 0 ]; then
    printf '%s%s ready to work.%s\n' "$BOLD" "$GREEN" "$RESET"
    exit 0
else
    printf '%s%s %d fatal check(s) failed — fix the [fail] lines above before coding.%s\n' "$BOLD" "$RED" "$FATAL_FAILURES" "$RESET"
    exit 1
fi
