// Copyright 2025 Crrow
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Domain types for resume version management.

use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use snafu::Snafu;
use strum_macros::{Display, FromRepr};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Newtypes
// ---------------------------------------------------------------------------

/// Strongly-typed resume identifier.
///
/// This is a domain-local alias that wraps [`rara_domain_shared::ResumeId`] so
/// that callers of this crate do not need to depend on `raradomain-shared`
/// directly.
pub type ResumeId = rara_domain_shared::id::ResumeId;

// ---------------------------------------------------------------------------
// Resume source
// ---------------------------------------------------------------------------

/// How a resume version was produced.
#[repr(u8)]
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Display, FromRepr, utoipa::ToSchema,
)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum ResumeSource {
    /// Manually authored by the user.
    Manual = 0,
    /// Generated by an AI model.
    AiGenerated = 1,
    /// An existing resume optimized/tailored for a specific job.
    Optimized = 2,
}

// ---------------------------------------------------------------------------
// Domain model
// ---------------------------------------------------------------------------

/// A versioned resume document (domain representation).
///
/// This mirrors the database `resume` table but lives in the domain layer
/// so that the service and repository trait can work without depending on
/// any infrastructure crate.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Resume {
    pub id:                  Uuid,
    pub title:               String,
    pub version_tag:         String,
    pub content_hash:        String,
    pub source:              ResumeSource,
    pub content:             Option<String>,
    pub parent_resume_id:    Option<Uuid>,
    pub target_job_id:       Option<Uuid>,
    pub customization_notes: Option<String>,
    pub tags:                Vec<String>,
    #[schema(value_type = Option<Object>)]
    pub metadata:            Option<serde_json::Value>,
    pub pdf_object_key:      Option<String>,
    pub pdf_file_size:       Option<i64>,
    pub trace_id:            Option<String>,
    pub is_deleted:          bool,
    #[schema(value_type = Option<String>)]
    pub deleted_at:          Option<Timestamp>,
    #[schema(value_type = String)]
    pub created_at:          Timestamp,
    #[schema(value_type = String)]
    pub updated_at:          Timestamp,
}

// ---------------------------------------------------------------------------
// Requests
// ---------------------------------------------------------------------------

/// Parameters for creating a new resume version.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct CreateResumeRequest {
    pub title:               String,
    pub content:             String,
    pub source:              ResumeSource,
    pub parent_resume_id:    Option<Uuid>,
    pub target_job_id:       Option<Uuid>,
    pub customization_notes: Option<String>,
    pub tags:                Vec<String>,
}

/// Parameters for uploading a PDF resume.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UploadPdfRequest {
    pub title: String,
    pub tags:  Vec<String>,
}

/// Parameters for a partial update of an existing resume.
///
/// Only the fields set to `Some` will be applied.
#[derive(Debug, Clone, Default, Serialize, Deserialize, utoipa::ToSchema)]
pub struct UpdateResumeRequest {
    pub title:               Option<String>,
    pub content:             Option<String>,
    pub source:              Option<ResumeSource>,
    pub target_job_id:       Option<Option<Uuid>>,
    pub customization_notes: Option<Option<String>>,
    pub tags:                Option<Vec<String>>,
}

// ---------------------------------------------------------------------------
// Filters
// ---------------------------------------------------------------------------

/// Criteria for listing/searching resume versions.
#[derive(Debug, Clone, Default, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResumeFilter {
    /// Only return resumes produced by this source.
    pub source:         Option<ResumeSource>,
    /// If `Some(true)`, return only derived resumes; if `Some(false)`, only
    /// root (baseline) resumes.
    pub has_parent:     Option<bool>,
    /// Filter to resumes targeting a specific job.
    pub target_job_id:  Option<Uuid>,
    /// Resumes must contain *all* of these tags.
    pub tags:           Option<Vec<String>>,
    /// Created at or after this timestamp.
    #[schema(value_type = Option<String>)]
    pub created_after:  Option<Timestamp>,
    /// Created at or before this timestamp.
    #[schema(value_type = Option<String>)]
    pub created_before: Option<Timestamp>,
}

// ---------------------------------------------------------------------------
// Diff
// ---------------------------------------------------------------------------

/// A simple line-level diff between two resume versions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResumeDiff {
    /// ID of the first resume (the "before" side).
    pub resume_a_id: Uuid,
    /// ID of the second resume (the "after" side).
    pub resume_b_id: Uuid,
    /// Individual hunks describing the changes.
    pub hunks:       Vec<DiffHunk>,
}

/// A single contiguous range of changed lines.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffHunk {
    /// 1-based line number in the *old* text where this hunk starts.
    pub old_start: usize,
    /// Number of lines removed from the old text.
    pub old_count: usize,
    /// 1-based line number in the *new* text where this hunk starts.
    pub new_start: usize,
    /// Number of lines added in the new text.
    pub new_count: usize,
    /// The actual diff lines (prefixed with ' ', '+', or '-').
    pub lines:     Vec<DiffLine>,
}

/// A single line within a [`DiffHunk`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DiffLine {
    /// Line present in both versions (context).
    Context(String),
    /// Line added in the new version.
    Added(String),
    /// Line removed from the old version.
    Removed(String),
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Errors that can occur in the resume domain.
#[derive(Debug, Snafu)]
#[snafu(visibility(pub))]
pub enum ResumeError {
    /// The requested resume was not found (or has been soft-deleted).
    #[snafu(display("resume not found: {id}"))]
    NotFound { id: Uuid },

    /// The content hash already exists -- the content is unchanged.
    #[snafu(display("duplicate content (hash already exists): {content_hash}"))]
    DuplicateContent { content_hash: String },

    /// The supplied content is invalid (empty, too large, etc.).
    #[snafu(display("invalid resume content: {reason}"))]
    InvalidContent { reason: String },

    /// The specified parent resume does not exist.
    #[snafu(display("parent resume not found: {parent_id}"))]
    ParentNotFound { parent_id: Uuid },

    /// Uploaded file exceeds the size limit.
    #[snafu(display("file too large: {size} bytes, max {max}"))]
    FileTooLarge { size: i64, max: i64 },

    /// Uploaded file is not a valid PDF.
    #[snafu(display("invalid file type: expected PDF, got {content_type}"))]
    InvalidFileType { content_type: String },

    /// Object storage upload/download failed.
    #[snafu(display("upload failed: {message}"))]
    UploadFailed { message: String },

    /// The requested resume does not have an associated PDF.
    #[snafu(display("PDF not found for resume: {id}"))]
    PdfNotFound { id: Uuid },

    /// A storage/infrastructure error occurred.
    #[snafu(display("storage error: {message}"))]
    Storage { message: String },
}

// ---------------------------------------------------------------------------
// DB model conversions
// ---------------------------------------------------------------------------

use rara_domain_shared::convert::{
    chrono_opt_to_timestamp, chrono_to_timestamp, timestamp_opt_to_chrono, timestamp_to_chrono,
    u8_from_i16,
};
use rara_model::resume::Resume as StoreResume;

fn resume_source_from_i16(value: i16) -> ResumeSource {
    let repr = u8_from_i16(value, "resume.source");
    ResumeSource::from_repr(repr).unwrap_or_else(|| panic!("invalid resume.source: {value}"))
}

/// Store `Resume` -> Domain `Resume`.
impl From<StoreResume> for Resume {
    fn from(r: StoreResume) -> Self {
        Self {
            id:                  r.id,
            title:               r.title,
            version_tag:         r.version_tag,
            content_hash:        r.content_hash,
            source:              resume_source_from_i16(r.source),
            content:             r.content,
            parent_resume_id:    r.parent_resume_id,
            target_job_id:       r.target_job_id,
            customization_notes: r.customization_notes,
            tags:                r.tags,
            metadata:            r.metadata,
            pdf_object_key:      r.pdf_object_key,
            pdf_file_size:       r.pdf_file_size,
            trace_id:            r.trace_id,
            is_deleted:          r.is_deleted,
            deleted_at:          chrono_opt_to_timestamp(r.deleted_at),
            created_at:          chrono_to_timestamp(r.created_at),
            updated_at:          chrono_to_timestamp(r.updated_at),
        }
    }
}

/// Domain `Resume` -> Store `Resume`.
impl From<Resume> for StoreResume {
    fn from(r: Resume) -> Self {
        Self {
            id:                  r.id,
            title:               r.title,
            version_tag:         r.version_tag,
            content_hash:        r.content_hash,
            source:              r.source as u8 as i16,
            content:             r.content,
            parent_resume_id:    r.parent_resume_id,
            target_job_id:       r.target_job_id,
            customization_notes: r.customization_notes,
            tags:                r.tags,
            metadata:            r.metadata,
            pdf_object_key:      r.pdf_object_key,
            pdf_file_size:       r.pdf_file_size,
            trace_id:            r.trace_id,
            is_deleted:          r.is_deleted,
            deleted_at:          timestamp_opt_to_chrono(r.deleted_at),
            created_at:          timestamp_to_chrono(r.created_at),
            updated_at:          timestamp_to_chrono(r.updated_at),
        }
    }
}

impl axum::response::IntoResponse for ResumeError {
    fn into_response(self) -> axum::response::Response {
        let status = match &self {
            ResumeError::NotFound { .. } => axum::http::StatusCode::NOT_FOUND,
            ResumeError::InvalidContent { .. } => axum::http::StatusCode::BAD_REQUEST,
            ResumeError::ParentNotFound { .. } => axum::http::StatusCode::BAD_REQUEST,
            ResumeError::DuplicateContent { .. } => axum::http::StatusCode::CONFLICT,
            ResumeError::FileTooLarge { .. } => axum::http::StatusCode::PAYLOAD_TOO_LARGE,
            ResumeError::InvalidFileType { .. } => axum::http::StatusCode::UNSUPPORTED_MEDIA_TYPE,
            ResumeError::UploadFailed { .. } => axum::http::StatusCode::INTERNAL_SERVER_ERROR,
            ResumeError::PdfNotFound { .. } => axum::http::StatusCode::NOT_FOUND,
            ResumeError::Storage { .. } => axum::http::StatusCode::INTERNAL_SERVER_ERROR,
        };
        let message = self.to_string();
        if status.is_server_error() {
            tracing::error!(http_status = status.as_u16(), error = %message, "resume request error");
        }
        let body = serde_json::json!({
            "error": { "status": status.as_u16(), "message": message }
        });
        (status, axum::Json(body)).into_response()
    }
}
