// Copyright 2025 Crrow
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Domain types for resume version management.

use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use snafu::Snafu;
use strum_macros::{Display, FromRepr};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Newtypes
// ---------------------------------------------------------------------------

/// Strongly-typed resume identifier.
///
/// This is a domain-local alias that wraps [`job_domain_shared::ResumeId`] so
/// that callers of this crate do not need to depend on `job-domain-shared`
/// directly.
pub type ResumeId = job_domain_shared::id::ResumeId;

// ---------------------------------------------------------------------------
// Resume source
// ---------------------------------------------------------------------------

/// How a resume version was produced.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Display, FromRepr)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum ResumeSource {
    /// Manually authored by the user.
    Manual = 0,
    /// Generated by an AI model.
    AiGenerated = 1,
    /// An existing resume optimized/tailored for a specific job.
    Optimized = 2,
}

// ---------------------------------------------------------------------------
// Domain model
// ---------------------------------------------------------------------------

/// A versioned resume document (domain representation).
///
/// This mirrors the database `resume` table but lives in the domain layer
/// so that the service and repository trait can work without depending on
/// any infrastructure crate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Resume {
    pub id:                  Uuid,
    pub title:               String,
    pub version_tag:         String,
    pub content_hash:        String,
    pub source:              ResumeSource,
    pub content:             Option<String>,
    pub parent_resume_id:    Option<Uuid>,
    pub target_job_id:       Option<Uuid>,
    pub customization_notes: Option<String>,
    pub tags:                Vec<String>,
    pub metadata:            Option<serde_json::Value>,
    pub trace_id:            Option<String>,
    pub is_deleted:          bool,
    pub deleted_at:          Option<Timestamp>,
    pub created_at:          Timestamp,
    pub updated_at:          Timestamp,
}

// ---------------------------------------------------------------------------
// Requests
// ---------------------------------------------------------------------------

/// Parameters for creating a new resume version.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateResumeRequest {
    pub title:               String,
    pub content:             String,
    pub source:              ResumeSource,
    pub parent_resume_id:    Option<Uuid>,
    pub target_job_id:       Option<Uuid>,
    pub customization_notes: Option<String>,
    pub tags:                Vec<String>,
}

/// Parameters for a partial update of an existing resume.
///
/// Only the fields set to `Some` will be applied.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateResumeRequest {
    pub title:               Option<String>,
    pub content:             Option<String>,
    pub source:              Option<ResumeSource>,
    pub target_job_id:       Option<Option<Uuid>>,
    pub customization_notes: Option<Option<String>>,
    pub tags:                Option<Vec<String>>,
}

// ---------------------------------------------------------------------------
// Filters
// ---------------------------------------------------------------------------

/// Criteria for listing/searching resume versions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ResumeFilter {
    /// Only return resumes produced by this source.
    pub source:         Option<ResumeSource>,
    /// If `Some(true)`, return only derived resumes; if `Some(false)`, only
    /// root (baseline) resumes.
    pub has_parent:     Option<bool>,
    /// Filter to resumes targeting a specific job.
    pub target_job_id:  Option<Uuid>,
    /// Resumes must contain *all* of these tags.
    pub tags:           Option<Vec<String>>,
    /// Created at or after this timestamp.
    pub created_after:  Option<Timestamp>,
    /// Created at or before this timestamp.
    pub created_before: Option<Timestamp>,
}

// ---------------------------------------------------------------------------
// Diff
// ---------------------------------------------------------------------------

/// A simple line-level diff between two resume versions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResumeDiff {
    /// ID of the first resume (the "before" side).
    pub resume_a_id: Uuid,
    /// ID of the second resume (the "after" side).
    pub resume_b_id: Uuid,
    /// Individual hunks describing the changes.
    pub hunks:       Vec<DiffHunk>,
}

/// A single contiguous range of changed lines.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffHunk {
    /// 1-based line number in the *old* text where this hunk starts.
    pub old_start: usize,
    /// Number of lines removed from the old text.
    pub old_count: usize,
    /// 1-based line number in the *new* text where this hunk starts.
    pub new_start: usize,
    /// Number of lines added in the new text.
    pub new_count: usize,
    /// The actual diff lines (prefixed with ' ', '+', or '-').
    pub lines:     Vec<DiffLine>,
}

/// A single line within a [`DiffHunk`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DiffLine {
    /// Line present in both versions (context).
    Context(String),
    /// Line added in the new version.
    Added(String),
    /// Line removed from the old version.
    Removed(String),
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/// Errors that can occur in the resume domain.
#[derive(Debug, Snafu)]
#[snafu(visibility(pub))]
pub enum ResumeError {
    /// The requested resume was not found (or has been soft-deleted).
    #[snafu(display("resume not found: {id}"))]
    NotFound { id: Uuid },

    /// The content hash already exists -- the content is unchanged.
    #[snafu(display("duplicate content (hash already exists): {content_hash}"))]
    DuplicateContent { content_hash: String },

    /// The supplied content is invalid (empty, too large, etc.).
    #[snafu(display("invalid resume content: {reason}"))]
    InvalidContent { reason: String },

    /// The specified parent resume does not exist.
    #[snafu(display("parent resume not found: {parent_id}"))]
    ParentNotFound { parent_id: Uuid },

    /// A storage/infrastructure error occurred.
    #[snafu(display("storage error: {message}"))]
    Storage { message: String },
}
