// Copyright 2025 Crrow
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Core request/response types shared across all AI providers.

use serde::{Deserialize, Serialize};

/// Role of a participant in a conversation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageRole {
    /// System-level instructions that set the AI's behaviour.
    System,
    /// Message from the human user.
    User,
    /// Message generated by the AI assistant.
    Assistant,
}

impl std::fmt::Display for MessageRole {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::System => write!(f, "system"),
            Self::User => write!(f, "user"),
            Self::Assistant => write!(f, "assistant"),
        }
    }
}

/// A single message in a conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Role of the message author.
    pub role:    MessageRole,
    /// Textual content of the message.
    pub content: String,
}

impl Message {
    /// Create a new system message.
    #[must_use]
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role:    MessageRole::System,
            content: content.into(),
        }
    }

    /// Create a new user message.
    #[must_use]
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role:    MessageRole::User,
            content: content.into(),
        }
    }

    /// Create a new assistant message.
    #[must_use]
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role:    MessageRole::Assistant,
            content: content.into(),
        }
    }
}

/// Request sent to an AI provider for a chat completion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionRequest {
    /// Model identifier (e.g. `"gpt-4o"`, `"claude-sonnet-4-20250514"`).
    pub model:         String,
    /// Ordered list of conversation messages.
    pub messages:      Vec<Message>,
    /// Sampling temperature (0.0 = deterministic, 1.0 = creative).
    /// `None` means use the provider's default.
    pub temperature:   Option<f32>,
    /// Maximum number of tokens to generate.
    pub max_tokens:    Option<u32>,
    /// Optional JSON schema that the model output should conform to.
    /// Used for structured / function-calling style outputs.
    pub output_schema: Option<serde_json::Value>,
}

impl CompletionRequest {
    /// Create a minimal completion request with the given model and
    /// messages.
    #[must_use]
    pub fn new(model: impl Into<String>, messages: Vec<Message>) -> Self {
        Self {
            model: model.into(),
            messages,
            temperature: None,
            max_tokens: None,
            output_schema: None,
        }
    }
}

/// Token usage statistics returned by a provider.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Number of tokens in the prompt / input.
    pub input_tokens:  u32,
    /// Number of tokens in the completion / output.
    pub output_tokens: u32,
    /// Total tokens (input + output). Some providers report this
    /// directly; otherwise it is computed.
    pub total_tokens:  u32,
}

/// Reason why the model stopped generating.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FinishReason {
    /// The model naturally finished its response.
    Stop,
    /// The response was truncated because it hit `max_tokens`.
    Length,
    /// The model invoked a tool / function call.
    ToolCall,
    /// Content was filtered by a safety system.
    ContentFilter,
}

impl std::fmt::Display for FinishReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Stop => write!(f, "stop"),
            Self::Length => write!(f, "length"),
            Self::ToolCall => write!(f, "tool_call"),
            Self::ContentFilter => write!(f, "content_filter"),
        }
    }
}

/// Response returned by an AI provider after a completion call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionResponse {
    /// The generated text content.
    pub content:       String,
    /// Model identifier that produced this response.
    pub model:         String,
    /// Token usage statistics.
    pub usage:         TokenUsage,
    /// Reason the model stopped generating.
    pub finish_reason: FinishReason,
}
