[private]
build:
    go build -o bin/deploy ./cmd/deploy

# ========================================================================================
# Pulumi
# ========================================================================================

[doc("initialize Pulumi stacks (run once)")]
init:
    pulumi login --local && pulumi stack init infra-dev && pulumi stack init app-dev

[doc("deploy infrastructure stack")]
infra-up:
    pulumi up -s infra-dev -y

[doc("preview infrastructure changes")]
infra-preview:
    pulumi preview -s infra-dev

[doc("destroy infrastructure stack")]
infra-destroy:
    pulumi destroy -s infra-dev -y

[doc("deploy application stack")]
app-up:
    pulumi up -s app-dev -y

[doc("preview application changes")]
app-preview:
    pulumi preview -s app-dev

[doc("destroy application stack")]
app-destroy:
    pulumi destroy -s app-dev -y

[doc("deploy infra + app stacks")]
setup: infra-up app-up

[doc("destroy app + infra stacks")]
destroy: app-destroy infra-destroy