package quality

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// renderMarkdown generates the full quality matrix markdown document.
func renderMarkdown(crates []CrateInfo) string {
	var b strings.Builder

	b.WriteString("# Module Quality Matrix\n\n")
	b.WriteString("A living dashboard that tracks the health of every crate in the Rara workspace. ")
	b.WriteString("Inspired by engineering maturity models, this matrix helps identify gaps in documentation, testing, and maintainability across the codebase.\n\n")
	b.WriteString("**Legend:** ✅ Present/Good | ⚠️ Partial | ❌ Missing/None\n\n")
	b.WriteString(fmt.Sprintf("> **Last updated:** %s (auto-generated by `devtool quality-matrix`)\n\n", time.Now().Format("2006-01-02")))

	renderQualityTable(&b, crates)
	b.WriteString("\n")
	renderAggregateStats(&b, crates)
	b.WriteString("\n")
	renderByLayer(&b, crates)
	b.WriteString("\n")
	renderPriorityActions(&b, crates)

	return b.String()
}

// renderQualityTable writes the main crate quality table.
func renderQualityTable(b *strings.Builder, crates []CrateInfo) {
	b.WriteString("## Quality Table\n\n")
	b.WriteString("| Crate | Layer | AGENT.md | Tests | Docs | LOC | Notes |\n")
	b.WriteString("|-------|-------|----------|-------|------|----:|-------|\n")

	for _, c := range crates {
		agentMD := "❌"
		if c.HasAgentMD {
			agentMD = "✅"
		}

		tests := "❌"
		if c.HasTests {
			tests = "✅"
		}

		docs := formatDocCoverage(c)
		notes := generateNotes(c)

		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s | %s | %s |\n",
			c.Name, c.Layer, agentMD, tests, docs, formatNumber(c.LOC), notes))
	}
}

// formatDocCoverage returns a status icon with fraction and percentage.
func formatDocCoverage(c CrateInfo) string {
	if c.PubItems == 0 {
		return "—"
	}
	pct := c.DocPercent()
	icon := "❌"
	if pct >= 50 {
		icon = "✅"
	} else if pct > 0 {
		icon = "⚠️"
	}
	return fmt.Sprintf("%s %d/%d (%d%%)", icon, c.DocItems, c.PubItems, pct)
}

// generateNotes produces a brief note for the crate based on its metrics.
func generateNotes(c CrateInfo) string {
	var notes []string

	if c.LOC > 5000 && !c.HasAgentMD {
		notes = append(notes, "Large crate missing AGENT.md")
	}
	if c.LOC > 3000 && !c.HasTests {
		notes = append(notes, "No tests")
	}
	if c.PubItems > 0 && c.DocPercent() >= 90 {
		notes = append(notes, "Excellent docs")
	}
	if c.PubItems > 0 && c.DocPercent() == 100 {
		notes = []string{"Fully documented"}
	}
	if c.LOC < 50 {
		notes = append(notes, "Mostly migrations or minimal Rust code")
	}

	if len(notes) == 0 {
		return "—"
	}
	return strings.Join(notes, "; ")
}

// renderAggregateStats writes the summary statistics section.
func renderAggregateStats(b *strings.Builder, crates []CrateInfo) {
	totalCrates := len(crates)
	withAgent := 0
	withTests := 0
	docOver50 := 0
	totalLOC := 0

	for _, c := range crates {
		if c.HasAgentMD {
			withAgent++
		}
		if c.HasTests {
			withTests++
		}
		if c.PubItems > 0 && c.DocPercent() >= 50 {
			docOver50++
		}
		totalLOC += c.LOC
	}

	b.WriteString("## Aggregate Statistics\n\n")
	b.WriteString("| Metric | Count | Percentage |\n")
	b.WriteString("|--------|------:|----------:|\n")
	b.WriteString(fmt.Sprintf("| **Total crates** | %d | — |\n", totalCrates))
	b.WriteString(fmt.Sprintf("| **With AGENT.md** | %d | %d%% |\n", withAgent, pct(withAgent, totalCrates)))
	b.WriteString(fmt.Sprintf("| **With tests** | %d | %d%% |\n", withTests, pct(withTests, totalCrates)))
	b.WriteString(fmt.Sprintf("| **Doc coverage > 50%%** | %d | %d%% |\n", docOver50, pct(docOver50, totalCrates)))
	b.WriteString(fmt.Sprintf("| **Total Rust LOC** | %s | — |\n", formatNumber(totalLOC)))
}

// renderByLayer writes the per-layer breakdown table.
func renderByLayer(b *strings.Builder, crates []CrateInfo) {
	type layerStats struct {
		name      string
		count     int
		docSum    int // sum of doc percentages
		withAgent int
		withTests int
	}

	layerMap := make(map[string]*layerStats)
	layerOrder := []string{"common", "domain", "kernel", "app", "server", "cmd", "extensions", "integrations"}

	for _, c := range crates {
		ls, ok := layerMap[c.Layer]
		if !ok {
			ls = &layerStats{name: c.Layer}
			layerMap[c.Layer] = ls
		}
		ls.count++
		if c.PubItems > 0 {
			ls.docSum += c.DocPercent()
		}
		if c.HasAgentMD {
			ls.withAgent++
		}
		if c.HasTests {
			ls.withTests++
		}
	}

	b.WriteString("### By Layer\n\n")
	b.WriteString("| Layer | Crates | Avg Doc Coverage | With AGENT.md | With Tests |\n")
	b.WriteString("|-------|-------:|-----------------:|--------------:|-----------:|\n")

	for _, name := range layerOrder {
		ls, ok := layerMap[name]
		if !ok {
			continue
		}
		avgDoc := 0
		if ls.count > 0 {
			avgDoc = ls.docSum / ls.count
		}
		b.WriteString(fmt.Sprintf("| %s | %d | %d%% | %d | %d |\n",
			name, ls.count, avgDoc, ls.withAgent, ls.withTests))
	}

	// Include any layers not in the predefined order
	for name, ls := range layerMap {
		found := false
		for _, n := range layerOrder {
			if n == name {
				found = true
				break
			}
		}
		if !found {
			avgDoc := 0
			if ls.count > 0 {
				avgDoc = ls.docSum / ls.count
			}
			b.WriteString(fmt.Sprintf("| %s | %d | %d%% | %d | %d |\n",
				name, ls.count, avgDoc, ls.withAgent, ls.withTests))
		}
	}
}

// renderPriorityActions generates actionable recommendations based on the data.
func renderPriorityActions(b *strings.Builder, crates []CrateInfo) {
	b.WriteString("## Priority Actions\n\n")

	// 1. AGENT.md gap
	var missingAgent []CrateInfo
	for _, c := range crates {
		if !c.HasAgentMD {
			missingAgent = append(missingAgent, c)
		}
	}
	sort.Slice(missingAgent, func(i, j int) bool { return missingAgent[i].LOC > missingAgent[j].LOC })

	if len(missingAgent) > 0 {
		targets := topN(missingAgent, 4)
		b.WriteString(fmt.Sprintf("1. **AGENT.md gap**: %d of %d crates lack an AGENT.md. High-priority targets: %s.\n",
			len(missingAgent), len(crates), formatCrateList(targets)))
	}

	// 2. Test gap
	var missingTests []CrateInfo
	for _, c := range crates {
		if !c.HasTests {
			missingTests = append(missingTests, c)
		}
	}
	sort.Slice(missingTests, func(i, j int) bool { return missingTests[i].LOC > missingTests[j].LOC })

	if len(missingTests) > 0 {
		targets := topN(missingTests, 4)
		b.WriteString(fmt.Sprintf("2. **Test gap**: %d crates have zero tests. Critical gaps: %s.\n",
			len(missingTests), formatCrateList(targets)))
	}

	// 3. Doc coverage
	var lowDoc []CrateInfo
	for _, c := range crates {
		if c.PubItems > 0 && c.DocPercent() < 50 {
			lowDoc = append(lowDoc, c)
		}
	}
	docOver50 := len(crates) - len(lowDoc)
	sort.Slice(lowDoc, func(i, j int) bool { return lowDoc[i].LOC > lowDoc[j].LOC })

	if len(lowDoc) > 0 {
		target := lowDoc[0]
		b.WriteString(fmt.Sprintf("3. **Doc coverage**: Only %d crates exceed 50%% doc coverage. The highest-impact target: `%s` (%s LOC, %d%%).\n",
			docOver50, target.Name, formatNumber(target.LOC), target.DocPercent()))
	}

	// 4. Common layer health
	commonNoTests := 0
	commonTotal := 0
	for _, c := range crates {
		if c.Layer == "common" {
			commonTotal++
			if !c.HasTests {
				commonNoTests++
			}
		}
	}
	if commonTotal > 0 && commonNoTests > commonTotal/2 {
		b.WriteString(fmt.Sprintf("4. **Common layer**: The foundational `common/` crates have gaps — %d of %d lack tests. Since every other layer depends on them, improving common/ has outsized impact.\n",
			commonNoTests, commonTotal))
	}
}

// topN returns the first n elements of the slice, or all if fewer.
func topN(crates []CrateInfo, n int) []CrateInfo {
	if len(crates) < n {
		return crates
	}
	return crates[:n]
}

// formatCrateList renders a list of crates with LOC for display.
func formatCrateList(crates []CrateInfo) string {
	parts := make([]string, len(crates))
	for i, c := range crates {
		parts[i] = fmt.Sprintf("`%s` (%s LOC)", c.Name, formatNumber(c.LOC))
	}
	return strings.Join(parts, ", ")
}

// formatNumber adds comma separators to large numbers.
func formatNumber(n int) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}
	// Insert commas from right to left
	var result strings.Builder
	for i, ch := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			result.WriteByte(',')
		}
		result.WriteRune(ch)
	}
	return result.String()
}

// pct computes integer percentage, safe against division by zero.
func pct(num, denom int) int {
	if denom == 0 {
		return 0
	}
	return (num * 100) / denom
}
