// Copyright 2025 Rararulab
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Session domain types — [`SessionKey`], [`SessionEntry`], [`ChannelBinding`].

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use super::error::SessionError;

// ---------------------------------------------------------------------------
// SessionKey
// ---------------------------------------------------------------------------

/// Opaque UUID identifier for a chat session.
///
/// Session keys are generated by [`SessionRepository::create()`] and should
/// never be constructed manually by callers. Use [`from_raw`](Self::from_raw)
/// only when reading from a trusted source (e.g. the database).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SessionKey(uuid::Uuid);

impl SessionKey {
    /// Generate a new random session key (UUID v4).
    #[must_use]
    pub fn new() -> Self { Self(uuid::Uuid::new_v4()) }

    /// Create a session key from a trusted string (e.g. database row).
    ///
    /// # Panics
    ///
    /// Panics if `raw` is not a valid UUID. Only use with trusted data.
    #[must_use]
    pub fn from_raw(raw: &str) -> Self {
        Self(uuid::Uuid::parse_str(raw).expect("SessionKey::from_raw: invalid UUID"))
    }

    /// Try to parse a session key from a string, returning an error on invalid
    /// UUID.
    ///
    /// Prefer this over [`from_raw`](Self::from_raw) when the input comes from
    /// an untrusted source (user input, URL parameters, etc.).
    pub fn try_from_raw(raw: &str) -> Result<Self, SessionError> {
        let uuid = uuid::Uuid::parse_str(raw).map_err(|_| SessionError::InvalidKey {
            message: raw.to_string(),
        })?;
        Ok(Self(uuid))
    }

    /// Return the inner [`uuid::Uuid`].
    #[must_use]
    pub fn uuid(&self) -> uuid::Uuid { self.0 }
}

impl std::fmt::Display for SessionKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { write!(f, "{}", self.0) }
}

impl Default for SessionKey {
    fn default() -> Self { Self::new() }
}

// ---------------------------------------------------------------------------
// SessionEntry
// ---------------------------------------------------------------------------

/// A persisted chat session with metadata.
///
/// Each session is uniquely identified by its [`SessionKey`] and tracks
/// message count, model configuration, and a short preview of the
/// conversation for UI display.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionEntry {
    /// Unique session key (serves as primary key in the database).
    pub key:           SessionKey,
    /// Human-readable title / label shown in session lists.
    pub title:         Option<String>,
    /// LLM model name used for this session (e.g. `"gpt-4o"`,
    /// `"claude-sonnet-4-5-20250929"`).
    pub model:         Option<String>,
    /// Optional system prompt override. When `None`, the service-level
    /// default system prompt is used.
    pub system_prompt: Option<String>,
    /// Running total of messages in this session.
    pub message_count: i64,
    /// Short preview text (typically the first user message, truncated)
    /// for display in session listings.
    pub preview:       Option<String>,
    /// Arbitrary JSON metadata for client-specific extensions.
    pub metadata:      Option<serde_json::Value>,
    /// When the session was first created.
    pub created_at:    DateTime<Utc>,
    /// When the session was last modified (message appended, metadata
    /// changed, etc.).
    pub updated_at:    DateTime<Utc>,
}

// ---------------------------------------------------------------------------
// ChannelBinding
// ---------------------------------------------------------------------------

/// Maps an external channel to a [`SessionKey`].
///
/// Channel bindings allow external messaging platforms (Telegram, Slack, etc.)
/// to route incoming messages to the correct session without the caller
/// needing to know the internal session key.
///
/// The composite key `(channel_type, account, chat_id)` is unique; upserting
/// a binding with the same composite key will update the target session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelBinding {
    /// Channel type identifier, e.g. `"telegram"`, `"slack"`, `"web"`.
    pub channel_type: String,
    /// External account or bot identifier within the channel
    /// (e.g. Telegram bot token hash, Slack workspace id).
    pub account:      String,
    /// External chat or conversation identifier within the channel
    /// (e.g. Telegram chat id, Slack channel id).
    pub chat_id:      String,
    /// The internal session key this binding resolves to.
    pub session_key:  SessionKey,
    /// When this binding was first created.
    pub created_at:   DateTime<Utc>,
    /// When this binding was last updated (e.g. re-pointed to a new session).
    pub updated_at:   DateTime<Utc>,
}
