// Copyright 2025 Rararulab
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Unified session types and traits.
//!
//! This module is the canonical source of truth for session-related types
//! used across the kernel and downstream crates (rara-sessions, rara-boot,
//! etc.). Session metadata is managed via [`SessionIndex`]. Message
//! persistence is handled by the tape subsystem (`rara_memory::tape`).

use std::sync::Arc;

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use snafu::Snafu;

// ---------------------------------------------------------------------------
// SessionError
// ---------------------------------------------------------------------------

/// Errors that can occur during session persistence operations.
#[derive(Debug, Snafu)]
#[snafu(visibility(pub))]
pub enum SessionError {
    /// The requested session was not found.
    #[snafu(display("session not found: {key}"))]
    NotFound { key: String },

    /// A session with this key already exists.
    #[snafu(display("session already exists: {key}"))]
    AlreadyExists { key: String },

    /// A storage/infrastructure error occurred.
    #[snafu(transparent)]
    Sqlx { source: sqlx::Error },

    /// The session key is malformed.
    #[snafu(display("invalid session key: {message}"))]
    InvalidKey { message: String },

    /// The fork point is out of range.
    #[snafu(display("invalid fork point: seq {seq} is out of range for session {key}"))]
    InvalidForkPoint { key: String, seq: i64 },

    /// A file I/O error occurred while reading/writing message JSONL files.
    #[snafu(display("message file I/O error: {source}"))]
    FileIo { source: std::io::Error },

    /// A JSON serialization/deserialization error occurred.
    #[snafu(display("json error: {source}"))]
    Json { source: serde_json::Error },
}

// ---------------------------------------------------------------------------
// SessionKey
// ---------------------------------------------------------------------------

/// Opaque UUID identifier for a chat session.
///
/// Session keys are generated by [`SessionRepository::create()`] and should
/// never be constructed manually by callers. Use [`from_raw`](Self::from_raw)
/// only when reading from a trusted source (e.g. the database).
base::define_id!(SessionKey);

// ---------------------------------------------------------------------------
// SessionEntry
// ---------------------------------------------------------------------------

/// A persisted chat session with metadata.
///
/// Each session is uniquely identified by its [`SessionKey`] and tracks
/// message count, model configuration, and a short preview of the
/// conversation for UI display.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionEntry {
    /// Unique session key (serves as primary key in the database).
    pub key:           SessionKey,
    /// Human-readable title / label shown in session lists.
    pub title:         Option<String>,
    /// LLM model name used for this session (e.g. `"gpt-4o"`,
    /// `"claude-sonnet-4-5-20250929"`).
    pub model:         Option<String>,
    /// Optional system prompt override. When `None`, the service-level
    /// default system prompt is used.
    pub system_prompt: Option<String>,
    /// Running total of messages in this session.
    pub message_count: i64,
    /// Short preview text (typically the first user message, truncated)
    /// for display in session listings.
    pub preview:       Option<String>,
    /// Arbitrary JSON metadata for client-specific extensions.
    pub metadata:      Option<serde_json::Value>,
    /// When the session was first created.
    pub created_at:    DateTime<Utc>,
    /// When the session was last modified (message appended, metadata
    /// changed, etc.).
    pub updated_at:    DateTime<Utc>,
}

// ---------------------------------------------------------------------------
// ChannelBinding
// ---------------------------------------------------------------------------

/// Maps an external channel to a [`SessionKey`].
///
/// Channel bindings allow external messaging platforms (Telegram, Slack, etc.)
/// to route incoming messages to the correct session without the caller
/// needing to know the internal session key.
///
/// The composite key `(channel_type, account, chat_id)` is unique; upserting
/// a binding with the same composite key will update the target session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelBinding {
    /// Channel type identifier, e.g. `"telegram"`, `"slack"`, `"web"`.
    pub channel_type: String,
    /// External account or bot identifier within the channel
    /// (e.g. Telegram bot token hash, Slack workspace id).
    pub account:      String,
    /// External chat or conversation identifier within the channel
    /// (e.g. Telegram chat id, Slack channel id).
    pub chat_id:      String,
    /// The internal session key this binding resolves to.
    pub session_key:  SessionKey,
    /// When this binding was first created.
    pub created_at:   DateTime<Utc>,
    /// When this binding was last updated (e.g. re-pointed to a new session).
    pub updated_at:   DateTime<Utc>,
}

// NOTE: The legacy `SessionRepository` trait and `SessionRepoRef` type alias
// have been removed. Message persistence is now handled by the tape subsystem
// (`rara_memory::tape::TapeService`). Session metadata is managed via
// `SessionIndex` below.

// ---------------------------------------------------------------------------
// SessionIndex — lightweight metadata-only session interface
// ---------------------------------------------------------------------------

/// Shared reference to a [`SessionIndex`] implementation.
pub type SessionIndexRef = Arc<dyn SessionIndex>;

/// Lightweight session metadata index — no message storage.
///
/// Unlike [`SessionRepository`], `SessionIndex` only manages session metadata
/// and channel bindings. Message persistence is handled by the tape subsystem.
/// This trait is the future replacement for the session-related subset of
/// `SessionRepository`.
#[async_trait]
pub trait SessionIndex: Send + Sync + 'static {
    /// Persist a new session entry.
    async fn create_session(&self, entry: &SessionEntry) -> Result<SessionEntry, SessionError>;

    /// Retrieve a session by its key, or `None` if it does not exist.
    async fn get_session(&self, key: &SessionKey) -> Result<Option<SessionEntry>, SessionError>;

    /// List sessions, ordered by `updated_at` descending.
    async fn list_sessions(
        &self,
        limit: i64,
        offset: i64,
    ) -> Result<Vec<SessionEntry>, SessionError>;

    /// Update mutable session fields.
    async fn update_session(&self, entry: &SessionEntry) -> Result<SessionEntry, SessionError>;

    /// Delete a session.
    async fn delete_session(&self, key: &SessionKey) -> Result<(), SessionError>;

    /// Upsert a channel binding.
    async fn bind_channel(&self, binding: &ChannelBinding) -> Result<ChannelBinding, SessionError>;

    /// Resolve a channel binding by `(channel_type, account, chat_id)`.
    async fn get_channel_binding(
        &self,
        channel_type: &str,
        account: &str,
        chat_id: &str,
    ) -> Result<Option<ChannelBinding>, SessionError>;

    /// Resolve a channel binding by `(channel_type, chat_id)` only, ignoring
    /// the account dimension.
    async fn get_binding_by_chat(
        &self,
        _channel_type: &str,
        _chat_id: &str,
    ) -> Result<Option<ChannelBinding>, SessionError> {
        Ok(None)
    }
}

// ---------------------------------------------------------------------------
// NoopSessionIndex
// ---------------------------------------------------------------------------

/// A no-op session index for testing — all operations succeed without
/// persisting.
pub struct NoopSessionIndex;

#[async_trait]
impl SessionIndex for NoopSessionIndex {
    async fn create_session(&self, entry: &SessionEntry) -> Result<SessionEntry, SessionError> {
        Ok(entry.clone())
    }

    async fn get_session(&self, _key: &SessionKey) -> Result<Option<SessionEntry>, SessionError> {
        Ok(None)
    }

    async fn list_sessions(
        &self,
        _limit: i64,
        _offset: i64,
    ) -> Result<Vec<SessionEntry>, SessionError> {
        Ok(vec![])
    }

    async fn update_session(&self, entry: &SessionEntry) -> Result<SessionEntry, SessionError> {
        Ok(entry.clone())
    }

    async fn delete_session(&self, _key: &SessionKey) -> Result<(), SessionError> { Ok(()) }

    async fn bind_channel(&self, binding: &ChannelBinding) -> Result<ChannelBinding, SessionError> {
        Ok(binding.clone())
    }

    async fn get_channel_binding(
        &self,
        _channel_type: &str,
        _account: &str,
        _chat_id: &str,
    ) -> Result<Option<ChannelBinding>, SessionError> {
        Ok(None)
    }
}
