# Copyright 2025 Rararulab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from execution.v1 import worker_pb2 as execution_dot_v1_dot_worker__pb2


class ExecutionWorkerServiceStub(object):
    """ExecutionWorkerService exposes sync/async capability execution operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/execution.v1.ExecutionWorkerService/Status',
                request_serializer=execution_dot_v1_dot_worker__pb2.StatusRequest.SerializeToString,
                response_deserializer=execution_dot_v1_dot_worker__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListCapabilities = channel.unary_unary(
                '/execution.v1.ExecutionWorkerService/ListCapabilities',
                request_serializer=execution_dot_v1_dot_worker__pb2.ListCapabilitiesRequest.SerializeToString,
                response_deserializer=execution_dot_v1_dot_worker__pb2.ListCapabilitiesResponse.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/execution.v1.ExecutionWorkerService/Invoke',
                request_serializer=execution_dot_v1_dot_worker__pb2.InvokeRequest.SerializeToString,
                response_deserializer=execution_dot_v1_dot_worker__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/execution.v1.ExecutionWorkerService/SubmitTask',
                request_serializer=execution_dot_v1_dot_worker__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=execution_dot_v1_dot_worker__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/execution.v1.ExecutionWorkerService/GetTask',
                request_serializer=execution_dot_v1_dot_worker__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=execution_dot_v1_dot_worker__pb2.GetTaskResponse.FromString,
                _registered_method=True)


class ExecutionWorkerServiceServicer(object):
    """ExecutionWorkerService exposes sync/async capability execution operations.
    """

    def Status(self, request, context):
        """Returns the current worker identity (name + runtime kind).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCapabilities(self, request, context):
        """Lists capability names currently registered on this worker instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Executes a capability synchronously and returns the result inline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """Submits a capability execution request as an asynchronous task.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Queries the current state/result of a previously submitted task.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=execution_dot_v1_dot_worker__pb2.StatusRequest.FromString,
                    response_serializer=execution_dot_v1_dot_worker__pb2.StatusResponse.SerializeToString,
            ),
            'ListCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCapabilities,
                    request_deserializer=execution_dot_v1_dot_worker__pb2.ListCapabilitiesRequest.FromString,
                    response_serializer=execution_dot_v1_dot_worker__pb2.ListCapabilitiesResponse.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=execution_dot_v1_dot_worker__pb2.InvokeRequest.FromString,
                    response_serializer=execution_dot_v1_dot_worker__pb2.InvokeResponse.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=execution_dot_v1_dot_worker__pb2.SubmitTaskRequest.FromString,
                    response_serializer=execution_dot_v1_dot_worker__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=execution_dot_v1_dot_worker__pb2.GetTaskRequest.FromString,
                    response_serializer=execution_dot_v1_dot_worker__pb2.GetTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'execution.v1.ExecutionWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('execution.v1.ExecutionWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionWorkerService(object):
    """ExecutionWorkerService exposes sync/async capability execution operations.
    """

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.v1.ExecutionWorkerService/Status',
            execution_dot_v1_dot_worker__pb2.StatusRequest.SerializeToString,
            execution_dot_v1_dot_worker__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.v1.ExecutionWorkerService/ListCapabilities',
            execution_dot_v1_dot_worker__pb2.ListCapabilitiesRequest.SerializeToString,
            execution_dot_v1_dot_worker__pb2.ListCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.v1.ExecutionWorkerService/Invoke',
            execution_dot_v1_dot_worker__pb2.InvokeRequest.SerializeToString,
            execution_dot_v1_dot_worker__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.v1.ExecutionWorkerService/SubmitTask',
            execution_dot_v1_dot_worker__pb2.SubmitTaskRequest.SerializeToString,
            execution_dot_v1_dot_worker__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/execution.v1.ExecutionWorkerService/GetTask',
            execution_dot_v1_dot_worker__pb2.GetTaskRequest.SerializeToString,
            execution_dot_v1_dot_worker__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
